modified deploy

diff --git a/.github/workflows/deploy-infra.yml b/.github/workflows/deploy-infra.yml
--- a/.github/workflows/deploy-infra.yml
+++ b/.github/workflows/deploy-infra.yml
@@ -23,6 +23,16 @@ jobs:
       - name: Checkout Code
         uses: actions/checkout@v3
 
+      - name: Validate CloudFormation Template
+        run: aws cloudformation validate-template --template-body file://cloudformation.yml
+
+      - name: Sanity check for forbidden properties
+        run: |
+          if grep -q AssociatePublicIpAddress cloudformation.yml; then
+            echo "ERROR: Found forbidden AssociatePublicIpAddress property in template."
+            exit 1
+          fi
+
       - name: Configure AWS OIDC Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
